CREATE DATABASE IF NOT EXISTS wewalk;
USE wewalk;

CREATE TABLE IF NOT EXISTS activity(
id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
caption CHAR(60) NOT NULL, 
location CHAR(30) NOT NULL,
start DATETIME NOT NULL,
end DATETIME NOT NULL,
price int UNSIGNED NOT NULL, 
content TEXT NOT NULL,
status TINYINT UNSIGNED NOT NULL DEFAULT 0,
cover CHAR(128) DEFAULT '',
gather_location CHAR(50) NOT NULL,
leaders CHAR(50) NOT NULL,
sleep_style CHAR(50) NOT NULL,
strength TINYINT NOT NULL,
difficulty TINYINT NOT NULL,
danger TINYINT NOT NULL,
view TINYINT NOT NULL,
type TINYINT NOT NULL
) ENGINE = innodb DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS blog(
id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
caption CHAR(60) NOT NULL DEFAULT '',
content TEXT NOT NULL,
author CHAR(30) DEFAULT '',
status TINYINT UNSIGNED NOT NULL DEFAULT 0, 
createtime DATETIME DEFAULT CURRENT_TIMESTAMP,
lastupdate DATETIME ON UPDATE CURRENT_TIMESTAMP,
stick_top BOOL NOT NULL DEFAULT false,
type TINYINT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS config(
name CHAR(30) NOT NULL PRIMARY KEY,
value CHAR(60) NOT NULL DEFAULT ''
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS message(
id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
sender CHAR(30) NOT NULL,
email CHAR(60) NOT NULL,
message TEXT NOT NULL,
createtime DATETIME DEFAULT CURRENT_TIMESTAMP,
flag TINYINT DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS admin(
id INT UNSIGNED auto_increment NOT NULL PRIMARY KEY,
username CHAR(15) NOT NULL UNIQUE,
password CHAR(64) NOT NULL
)ENGINE = InnoDB default CHARSET=utf8;